initial_state = {
    "entrepreneur": {
        "name": "SaloTech",
        "description": "AI automation platform for B2B teams",
        "target_market": "Mid-market B2B SaaS companies",
        "revenue_model": "Subscription + usage-based",
        "current_traction": "Early revenue, 10 paying customers",
        "investment_needed": 500000.0,
        "use_of_funds": "Product, sales, and GTM",
        "stage": "Seed",
        "valuation_ask": 2_000_000.0,
        "equity_offered": 0.10,
        "monthly_revenue": 15_000.0,
        "monthly_burn": 10_000.0,
        "gross_margin": 0.35,
        "team_size": 4,
        "founder_experience_score": 0.7,
        "tech_moat_score": 0.6,
        "competition_intensity_score": 0.4,
        "regulatory_risk_score": 0.2,
        "negotiations": [],
        "concessions_history": [],
    },
    "judges": [
        {
            "name": "Judge_A",
            "risk_tolerance": 0.6,
            "return_target": 0.3,
            "scalability_focus": 0.8,
            "negotiation_aggressiveness": 0.4,
            "showmanship_preference": 0.5,
            "sector_preference": ["ai", "automation", "b2b"],
            "ticket_min": 50_000.0,
            "ticket_max": 200_000.0,
            "time_horizon_years": 5.0,
            "impact_focus": 0.3,
            "control_preference": 0.5,
            "allocated_budget_remaining": 500_000.0,
            "current_interest_level": 0.0,
            "trust_in_entrepreneur": 0.5,
            "perceived_risk_score": 0.5,
            "perceived_upside_score": 0.5,
            "negotiations": [],
            "offers_made": [],
            "deal_breakers_triggered": [],
            "narrative_evaluations": [],
            "offer_rationales": [],
        },
        {
            "name": "Judge_B",
            "risk_tolerance": 0.3,
            "return_target": 0.5,
            "scalability_focus": 0.7,
            "negotiation_aggressiveness": 0.7,
            "showmanship_preference": 0.7,
            "sector_preference": ["ai", "analytics"],
            "ticket_min": 30_000.0,
            "ticket_max": 150_000.0,
            "time_horizon_years": 7.0,
            "impact_focus": 0.5,
            "control_preference": 0.8,
            "allocated_budget_remaining": 300_000.0,
            "current_interest_level": 0.0,
            "trust_in_entrepreneur": 0.4,
            "perceived_risk_score": 0.5,
            "perceived_upside_score": 0.5,
            "negotiations": [],
            "offers_made": [],
            "deal_breakers_triggered": [],
            "narrative_evaluations": [],
            "offer_rationales": [],
        },
    ],
    "round": 0,
    "max_rounds": 1,
    "finished": False,
}